title: Graft Documentation
author: Satoru Kawahara
description: Safe, structural code transformation using Tree-sitter
url: "https://nymphium.github.io/graft"
repository: "https://github.com/Nymphium/graft"
google_analytics:
encoding: "utf-8"
future: true
theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
